/*
 * \file
 * \brief SQL Printer.
 * \author Copyright © 2008 Bombela <bombela@free.fr>
 * \date 2008
 *
 * This file is part of MeriseAcide.
 *
 * MeriseAcide is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * MeriseAcide is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with MeriseAcide; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Purpose:
 *
 * Class d'impression SQL.
 *
 * $Id: SQLPrint.cpp 84 2008-07-25 22:12:56Z bombela $
 */

#include "SQLPrint.h"

#include <iostream>
#include <iterator>

#include "DateTime.h"

using namespace std;

namespace MeriseAcide
{

SQLPrint::SQLPrint(void): mOStream(0) { }

SQLPrint::SQLPrint(const std::string& FileName)
{
	Open(FileName);
}

SQLPrint::SQLPrint(std::ostream& os)
{
	Open(os);
}

SQLPrint::~SQLPrint(void)
{
	Close();
}

bool SQLPrint::Open(const std::string& FileName)
{
	Close();

	mFileName = FileName;
	mFileStream.open( mFileName.c_str() );

	if ( mFileStream.is_open() )
	{
		mPutComa = false;
		mOStream = &mFileStream;
		PutHeader();
	}
	
	return IsOpen();
}

bool SQLPrint::Open(std::ostream& os)
{
	Close();

	mOStream = &os;
	if (mOStream)
	{
		mPutComa = false;
		PutHeader();
	}
	return IsOpen();
}

void SQLPrint::Close()
{
	if ( IsOpen() )
	{
		mOStream = 0;
		mFileStream.close();
		mFileName = "";
	}
}

bool SQLPrint::IsOpen(void) const
{
	return mOStream;
}

void SQLPrint::NeedComa(void)
{
	mPutComa = true;
}

void SQLPrint::PutComaIfNeeded(void)
{
	if (mPutComa)
	{
		mPutComa = false;
		*mOStream << ",\n";
	}
}

void SQLPrint::ResetComa()
{
	mPutComa = false;
}

void SQLPrint::BreakLine()
{
	*mOStream << "\n";
}

void SQLPrint::PutHeader(void)
{
	DateTime dt;
	dt.LoadFromNow();

	PutComment("Generated by MeriseAcide. ");
	PutComment(dt.Fmt("%F %H:%M %Z") + ".");
	BreakLine(); 
}

}
